# -*- coding: utf-8 -*-
"""BI E_commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXNinw8c28-wrK1FvPavk_HM4WNbj0kz

1/importing necessary libreries
"""

import numpy as np
import pandas as pd

"""2/Uploading the datasets and inspecting raw data"""

from google.colab import files
uploaded = files.upload()

df_orders = pd.read_csv('./ecommerce_orders_10k_updated.csv')

df_marketing=pd.read_csv('marketing_campaign_dataset.csv')

df_orders.shape

df_marketing.shape

df_orders.head(10)

df_marketing.head(7)

df_orders.info()

df_marketing.info()

"""2/checking for umpty ,null values,and duplicates"""

df_orders.isnull().sum()

df_marketing.isnull().sum()

df_orders.duplicated().sum()

df_marketing.duplicated().sum()

""""No missing values in this datasets nor duplicates"

3/Outliers Handling
"""

df_orders = df_orders[df_orders["qty"] > 0]
df_orders = df_orders[df_orders["price"] > 0]
df_orders = df_orders[df_orders["total_price"] > 0]

"""4/Standardization"""

# ---- RENAME MARKETING COLUMNS ----
df_marketing = df_marketing.rename(columns={
    "Campaign_ID": "campaign_id",
    "Campaign_Type": "campaign_name",
    "Channel_Used": "channel",
    "Acquisition_Cost": "ad_spend",
    "Clicks": "clicks",
    "Impressions": "impressions",
    "Date": "campaign_date"
})

df_orders["order_date"] = pd.to_datetime(df_orders["order_date"])

df_orders["year"] = df_orders["order_date"].dt.year
df_orders["month"] = df_orders["order_date"].dt.month
df_orders["order_value"] = df_orders["price"] * df_orders["qty"]
df_orders["category"] = df_orders["category"].str.title()
df_orders["country"] = df_orders["country"].str.upper()

"""5/Building Tables"""

fact_orders = df_orders[[
    "order_id",
    "user_id",
    "product_id",
    "order_date",
    "qty",
    "price",
    "total_price"
]]

dim_marketing = df_marketing[[
    "campaign_id",
    "campaign_name",
    "channel"
]]

df_marketing["campaign_date"] = pd.to_datetime(df_marketing["campaign_date"])

fact_marketing = df_marketing[[
    "campaign_id",
    "campaign_date",
    "ad_spend",
    "impressions",
    "clicks"
]]

dim_customer = df_orders[[
    "user_id",
    "country",
    "customer_segment"
]]

dim_product = df_orders[[
    "product_id",
    "category",
    "price"
]]

# ---- DIM DATE ----
all_dates = pd.concat([
    df_orders["order_date"],
    df_marketing["campaign_date"]
])

dim_date = pd.DataFrame({"date": all_dates.drop_duplicates()})
dim_date["year"] = dim_date["date"].dt.year
dim_date["month"] = dim_date["date"].dt.month
dim_date["quarter"] = dim_date["date"].dt.to_period("Q").astype(str)
dim_date["day_name"] = dim_date["date"].dt.day_name()

"""6/Load clean data"""

fact_orders.to_csv("fact_orders.csv", index=False)
dim_customer.to_csv("dim_customer.csv", index=False)
dim_product.to_csv("dim_product.csv", index=False)
dim_date.to_csv("dim_date.csv", index=False)
fact_marketing.to_csv("fact_marketing.csv", index=False)
dim_marketing.to_csv("dim_marketing.csv", index=False)

"""### 7/Generate Data Dictionary

This section generates a data dictionary for all processed DataFrames (`df`, `fact_orders`, `dim_customer`, `dim_product`, `dim_date`), combining column information into an Excel file.
"""

data_dictionaries = []

def create_data_dictionary(dataframe, df_name):
    dict_df = pd.DataFrame({
        'Table Name': df_name,
        'Column Name': dataframe.columns,
        'Data Type': dataframe.dtypes.values,
        'Non-Null Count': dataframe.count().values,
        'Unique Values': [dataframe[col].nunique() for col in dataframe.columns],
        'Description': '' # Placeholder for manual descriptions
    })
    return dict_df

# Create data dictionaries for each DataFrame
data_dictionaries.append(create_data_dictionary(fact_orders, 'Fact Orders'))
data_dictionaries.append(create_data_dictionary(dim_customer, 'Dim Customer'))
data_dictionaries.append(create_data_dictionary(dim_product, 'Dim Product'))
data_dictionaries.append(create_data_dictionary(dim_date, 'Dim Date'))
data_dictionaries.append(create_data_dictionary(fact_marketing, 'Fact Marketing'))
data_dictionaries.append(create_data_dictionary(dim_marketing, 'Dim Marketing'))


# Concatenate all data dictionaries into a single DataFrame
full_data_dictionary = pd.concat(data_dictionaries, ignore_index=True)

# Save the full data dictionary to an Excel file
output_filename = 'data_dictionary.xlsx'
full_data_dictionary.to_excel(output_filename, index=False)

print(f"Data dictionary saved to {output_filename}")

# Display the first few rows of the data dictionary
display(full_data_dictionary.head())